# Generated by Django 4.2.8 on 2024-02-02 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_date_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 3, 1, 13, 3, 635818, tzinfo=datetime.timezone.utc)),
        ),
    ]
