# Generated by Django 4.2.8 on 2024-02-02 23:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 3, 23, 18, 57, 740062, tzinfo=datetime.timezone.utc)),
        ),
    ]
