# Generated by Django 4.2.8 on 2024-02-03 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 2, 4, 6, 42, 54, 702251, tzinfo=datetime.timezone.utc)),
        ),
    ]
