# Generated by Django 4.2.8 on 2024-02-03 21:48

import appointments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default=appointments.models.get_tommorrow),
        ),
    ]
