# Generated by Django 4.2.8 on 2024-02-03 06:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_hours', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True, null=True), size=7)),
                ('closing_hours', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True, null=True), size=7)),
                ('days_closed', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(blank=True, null=True), size=None)),
            ],
        ),
    ]
