# Generated by Django 4.2.8 on 2024-02-03 06:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_preferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppreferences',
            name='days_closed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
