# Generated by Django 4.2.8 on 2024-02-05 23:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operating_hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatinghours',
            name='closing_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True, null=True), size=7),
        ),
        migrations.AlterField(
            model_name='operatinghours',
            name='opening_hours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(blank=True, null=True), size=7),
        ),
    ]
