# Generated by Django 4.2.8 on 2024-02-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operating_hours', '0004_rename_day_name_holidayhours_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidayhours',
            old_name='closed_hours',
            new_name='closing_hours',
        ),
    ]
